# Generated by Django 3.0.2 on 2020-03-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
